version: "2.4"

################################################################################

services:
  lerobot:
    hostname: lerobot
    runtime: nvidia
    image: common_lerobot:latest
    container_name: "${PROJECT}_lerobot"
    privileged: false
    environment:
      # Display X Server GUI.
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      # Configure Nvidia Docker interface.
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_REQUIRE_CUDA=cuda>=11.0
      - SSH_AUTH_SOCK=/ssh-agent
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    shm_size: '8gb'
    volumes:
      - ./scripts:/root/scripts
      - "../:/root/work"
      - "/robot-qnap-2/kamijo/dataset:/root/dataset"
      - "/tmp/.X11-unix:/tmp/.X11-unix"
      - "$SSH_AUTH_SOCK:/ssh-agent"

        # devices:
      # - "/dev/usbcam:/dev/usbcam"
      # - "/dev/video0:/dev/video0"
      # - "/dev/video1:/dev/video1"
      # - "/dev/video2:/dev/video2"
      # - "/dev/video3:/dev/video3"
      # - "/dev/video4:/dev/video4"
      # - "/dev/video5:/dev/video5"
      # - "/dev/media0:/dev/media0"
      # - "/dev/media1:/dev/media1"

    working_dir: /root/work
    command: /root/scripts/initialize-docker-container.sh
